### ISSUE TITLE
decision on project flow ( project pipeline state)

### ISSUE THREAD

**Issue by ll911** [bcgov/smk-legacy-ui#11]
current state as default, please confirm

New issues
IceBox
Backlog
In Progress
Review/QA
Done

**Comment by NicoledeGreef** [comment]
Seems reasonable to me to adopt these states.

**Comment by cpspicer** [comment]
We might add a few for items out for external UAT.  Nicole and I will discuss as we groom the new issues prior to assignment to Milestone 1.0

**Comment by cpspicer** [comment]
Going to close for now and use the defaults.
