### ISSUE TITLE
Zoom with Box not supported

### ISSUE THREAD

**Issue by fmadelung** [bcgov/smk-legacy-ui#134]
In the Tools tab of the configuration utility, under zooming tool options there is an option for 'Zoom with Box'.  This zoom with box functionality does not appear to be supported in the map window.

**Comment by qqnluaq** [comment]
Hold down SHIFT key to drag a box on the map

**Comment by fmadelung** [comment]
This is resolved.  Testers error.  Marking this issue as closed.
