### ISSUE TITLE
Unable to add in our Web Map Services

### ISSUE THREAD

**Issue by pspry** [bcgov/smk-legacy-ui#172]
Unable to add either of our, MoTI, WMS

https://prdoas2.apps.th.gov.bc.ca/ogs-geoV06/wms
produces this message:
{ "status": "ERROR", "message": "Server returned HTTP response code: 401 for URL: https://prdoas2.apps.th.gov.bc.ca/ogs-geoV06/wms?service=WMS&request=GetCapabilities" }
This is likely due to the need to expose the SiteMinder BASIC authentication challenge

http://maps.th.gov.bc.ca/geoV05/wms
produces this message
{ "status": "ERROR", "message": "Connection reset" }
This site allows public anonymous access, so I don't know what the problem could be here. I was able to add http://maps.geogratis.gc.ca/wms/railway_en without issue.

## How to reproduce

- SMK version I'm using: http://smk.pathfinder.gov.bc.ca/smk-ui/#
- Browser (with version) I'm using: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 7 (Gov't issue)
- step 1: Try to add either of the URLs mentioned above

## What behaviour I'm expecting and which behaviour I'm seeing
Expect list of layers and instead see nothing.

**Comment by cpspicer** [comment]
Link to #27

**Comment by dhlevi** [comment]
I just gave the "http://maps.th.gov.bc.ca/geoV05/wms" url a try from my local dev instance, and it worked without issue. I'm suspecting the problem is a communication issue in the deployment locationwith the SMK service, which attempts to proxy the getCap request. We'll have to look on the deployed server and see if it's blocking requests.

Because currently SMK doesn't have siteminder authentication or webade support, secure services are not available.

**Comment by dhlevi** [comment]
Just ran a test on the deployment location, and that appears to be the case:

```
$ curl http://maps.th.gov.bc.ca/geoV05/wms
curl: (56) Recv failure: Connection reset by peer
```

Not a problem with SMK directly, but the admin ui environment. We'll figure out why it's not allowed to talk to your server, and once that's squared away the service should be usable!

**Comment by ghost** [comment]
We had issues similiar to this a few months back.. it was related to SNAT..
Our DMZ servers could not access WAM hosted domains. WAM missed a network policy on their end when they change our servers from old to new. There are groups of VIPS managed by WAM that need SNAT enabled.

**Comment by ghost** [comment]
Also, does this SMK proxy (which I hope is only used for authoring SMK sites) : http://smk.pathfinder.gov.bc.ca/smks-api/LayerLibrary/wms/?url=http%3A%2F%2Fopenmaps.gov.bc.ca%2Fgeo%2Fpub%2Fows%3Fservice%3DWMS%26request%3DGetCapabilities require POST enabled in CORS? I see the MOT WMS does not support POST in CORS declaration - current MOT WMS CORS :
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: X-Requested-With

**Comment by dhlevi** [comment]
Yes, the proxy is only in place for authoring via the service. Exported applications don't access the service.

The proxy uses javas urlopenStream() which should be a get, but I can update the code to enforce a get in the event it fires a post.

**Comment by ghost** [comment]
If this is just for UI/proxy authoring, then I don't think this is necessary, PLUS enforcing a GET should not be required for WMS.. since most implementations should be supporting POST / GET ..

**Comment by cpspicer** [comment]
@pspry Does the info in the above thread help?  Have you exported an SMK application and tried connectivity from your own web server?  Let me know so I can either close or push into the backlog for a second round.

**Comment by pspry** [comment]
We will be moving MoTI web map services to new hosts soon and can visit our CORS support then. So may as well push this one into the backlog for now.

**Comment by cpspicer** [comment]
Thanks Peter - I'll move to the icebox, but please remember to re-test the CORS support.  Also since this issue sounds like its an open shift related item, you could build a test app, export it, load on your own webserver and modify the JS to test external to Openshift.  Not sure if that would help?

**Comment by pspry** [comment]
Hi Chris, looks like it is an open shift problem, not SMK. I was able to bring in one of our WMS layers in an exported SMK.

**Comment by cpspicer** [comment]
Excellent!  Export for the win!
