### ISSUE TITLE
config of queries

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-legacy-ui#232]
## Minimal example reproducing the issue

See site ALRC draft 5;

![image](https://user-images.githubusercontent.com/26335003/43869509-b802d036-9b27-11e8-9a72-b2d352602277.png)

results in:

![image](https://user-images.githubusercontent.com/26335003/43869783-272710ca-9b29-11e8-8163-054a700f6632.png)

 i.e. the Search link is not active until a user has specified a value for each of the query criteria (regardless of Any/All setting in the Query configuration screen).

**Comment by dhlevi** [comment]
I actually passed in an update this afternoon to address exactly this issue. We didnt deploy it yet in case we had any other changes to make, but we can run a build tomorrow.

You can prevent the value from being required by setting the parameter "value" attribute in the json from NULL to an empty string

**Comment by NicoledeGreef** [comment]
Oh that's helpful- thanks.  If I understand correctly then, it's implementable post-export.

**Comment by dhlevi** [comment]
Yes, you can make those changes to queries post export, but in the next deploy parameters will be defaulted to use empty strings so it shouldnt be a problem.

There are several behaviours that the query supports that we cant as easily show in the current UI, like for instance linking multiple attributes to a single text box for a "google like" search box. Eventually we'd like to redo that UI so it covers all options, but its a lot of stuff to change so for now the UI handles the 90% and everything else can be done post export.

**Comment by NicoledeGreef** [comment]
that's great to hear as well.  sounds like it's leaning towards "uber-search" (one of our original requirements https://github.com/bcgov/smk/issues/46).

**Comment by NicoledeGreef** [comment]
I was able to pick up the change by deleting my existing Query in site "alrc draft 5" and recreating it.  The text box argument (Business Name) seems to be behaving as expected.  However, the auto-fill drop-downs (Health Authority, Type and City) are still acting like mandatory choices (see screenshot below).

When the arguments are set to AND, I can search but it returns no results.

![image](https://user-images.githubusercontent.com/26335003/44224229-abf7fb00-a13e-11e8-9913-0e8e4a57fe05.png)

When the arguments are set to ANY, I can search but it returns all records.

![image](https://user-images.githubusercontent.com/26335003/44224831-866bf100-a140-11e8-9e35-90dd248f6cd8.png)

**Comment by qqnluaq** [comment]
I have deployed a fix for this issue.

The problem before was that leaving the business name empty was doing a CONTAINS match of an empty string against BUSINESS_NAME, which is always true. So if the query is matching ANY of the clauses, then it would always match everything.

Ive changed the behaviour of query to address this problem. Now, if a parameter is null (empty), then the clause in the query that uses that parameter is completely dropped from the query. If all clauses of the query are dropped, then the query fails.

This query now functions at expected: https://smk-demo.pathfinder.gov.bc.ca/smk-ui/viewer.html?config=../smks-api/MapConfigurations/alrc-draft-5/

Any parameters left empty are ignored, and parameters that are provided allow their clauses to be used, and are AND'd together.

**Comment by NicoledeGreef** [comment]
Thanks @qqnluaq !

**Comment by qqnluaq** [comment]
Just a note: a consequence of this change is that there is no way to make a query that searches for an empty attribute. This will require extending the query syntax to allow an 'isNull' check.

**Comment by NicoledeGreef** [comment]
I think this approach still covers the majority of cases.
