### ISSUE TITLE
Setting a default active tool

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-legacy-ui#243]
Question: is there a setting in version <= 0.9 that will set the About Panel to be open by default when the map is loaded?

## How to reproduce

- SMK version I'm using:
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Win 7 Enterprise
- Visit [http://moh-qa.apps.gov.bc.ca/alrc/?](http://moh-qa.apps.gov.bc.ca/alrc/)
-  It would be good to have the option to start the session with the About panel active and open:

![image](https://user-images.githubusercontent.com/26335003/45992668-f7f06680-c03f-11e8-9079-b75a13afaea9.png)

**Comment by dhlevi** [comment]
@NicoledeGreef  There is an "activeTool" attribute that's part of the Map Viewer where you can set this value.
```
viewer: 
{
    ...
    activeTool: "about"
    ...
}
```

**Comment by NicoledeGreef** [comment]
that did the trick!  thx
