### ISSUE TITLE
Create repo in GitHub for Translink App code

### ISSUE THREAD

**Issue by cpspicer** [bcgov/smk-legacy-ui#318]

**Comment by NicoledeGreef** [comment]
https://github.com/bcgov/smk-tlink

Ben has been invited as a Writer

initially i called the repo smk-cvrp but have renamed it to tlink as I think it would be better to include tlink in the root and cvrp as the site name.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - can you pls check to see if you can write to this directory?

**Comment by qqnluaq** [comment]
Yes, I can. I made an initial commit to the develop branch. However, I don't have access to the project settings, so I can't enable GitHub pages to publish this site.

**Comment by NicoledeGreef** [comment]
@ll911  - can you please review and ensure @qqnluaq is set up properly in https://github.com/bcgov/smk-tlink

**Comment by NicoledeGreef** [comment]
a branch called 'gh-pages' has now been created.  @qqnluaq - is that sufficient?

**Comment by qqnluaq** [comment]
Looks good! https://bcgov.github.io/smk-tlink/
