### ISSUE TITLE
change Github pages config for bcgov/smk-client

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk-legacy-ui#324]
On the repo https://github.com/bcgov/smk-client, (**NOT** this repo, https://github.com/bcgov/smk), I'd like the Github pages config changed.

This screenshot shows what I'd the config changed to:
![image](https://user-images.githubusercontent.com/20274603/75827986-b3521a00-5d5f-11ea-8580-bd4537960bd4.png)

Please change the circled option to the value shown

**Comment by NicoledeGreef** [comment]
![image](https://user-images.githubusercontent.com/26335003/75914624-ea7d0580-5e09-11ea-8f7b-13fae4a9fcdf.png)

let me know if it needs tweaking.  i think it's done.

**Comment by qqnluaq** [comment]
Thanks!
