### ISSUE TITLE
Search - Search by Attribute UI

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-legacy-ui#45]
Very similar to existing DMF applications - see BC Parks as an example.

**Comment by cpspicer** [comment]
Link to DMF in Test:  https://test.apps.gov.bc.ca/ext/dmf-wizard/

**Comment by cpspicer** [comment]
![for board](https://user-images.githubusercontent.com/26190669/35819845-bc1a957e-0a58-11e8-9a10-7a9fb3e87909.JPG)

**Comment by NicoledeGreef** [comment]
dependency on connectivity to MPCM endpoint. #80

**Comment by cpspicer** [comment]
Lets set up a design session and discuss

**Comment by cpspicer** [comment]
Looking good.  A few quick observations:
1)  Can't find option to have the app poll the service to determine live contents for drop down lists (maybe need instructions?)
2) Would be nice to have an option for the author to choose an attribute to display along with the returned feature lists.  Similar to DMF returned results list:
![image](https://user-images.githubusercontent.com/26190669/40515015-0b6da330-5f60-11e8-9b60-85533fc9a0ee.png)

3) Tool is described as a 'Filter by' in the UI.  Should we change this to 'Search using'?

![image](https://user-images.githubusercontent.com/26190669/40514925-c0fcd96a-5f5f-11e8-85a8-3520d30e52d6.png)

4) Execute text could be changed to 'Search'

5) Could add a clear button in UI

**Comment by qqnluaq** [comment]
There is a configuration property to set the 'title attribute', ie the atttribute that is shown in the list above. This needs to be exposed in the admin UI.

**Comment by dhlevi** [comment]
Re the first issue on @cpspicer comment above:

We've added a button in the admin UI to pull values. Currently it's activated for WMS features, and on a follow up next week we'll add in vector. I took a dive into the DMF code and it looks like it's configured to use the ArcGIS service calls to populate the list (geoprocess tools should let us get around the query limits), so we can use that same method (not always ideal as it is possible for it to miss values on large datasets, but I'll try and work out a sensible query).

However, because we want this to automatically update on the client side, I think this code should be removed from the Admin UI and moved into the client. On startup, the client could attempt to fetch a list that will always be up to date for a dropdown attribute.

**Comment by cpspicer** [comment]
Agree code should be client side, with a mode option setting in the author.

**Comment by cpspicer** [comment]
QA Failure.  App builder won't open the screen to configure Queries for a layer.  e.g. Points of diversion.  Clicking yields no response or error from the UI.

**Comment by dhlevi** [comment]
@cpspicer Caught a bug in the admin ui related to the removal of surround editor panel that's affecting all modal dialogs. It's been patched, will do a build/deploy by Monday at the latest so you should see this issue fixed shortly.

**Comment by cpspicer** [comment]
I can now create queries again - testing continues.

I can manually add drop down values for attributes, but the actual attribute values are blank when you click on the drop down to make a choice.  The choices are there, and you can select a seemingly blank entry.  If you hit return the drop down box opens, but if you click in a text field and hit return the query will run and return results from that 'invisible' drop down attribute.

Also, still no toggle in the UI to have a drop down box fed from the live dataset for MPCM datasets. 

![image](https://user-images.githubusercontent.com/26190669/42789229-e4998444-8918-11e8-91ad-8840515e01b7.png)

I do like the new title attribute.  Thanks for adding!

**Comment by qqnluaq** [comment]
The title for a parameter select choice is now optional, and will be derived from value if missing.

https://github.com/bcgov/smk/wiki/SMK-Client-Configuration#choices-select-layer-query-parameter

**Comment by NicoledeGreef** [comment]
The queries are working well.  The UI styling needs a little bit of tweaking.  See "Assisted Living..." site".  At 100% zoom level in chrome the Query and results panel is cut-off due to the number of attributes listed, and the Title is displaced upwards.

![image](https://user-images.githubusercontent.com/26335003/44938934-9685f200-ad36-11e8-9ec8-118641e15a0f.png)

Would like to decrease the font-size for the Title and for the choices in the drop-down boxes as well.  Can this be done through the .css?

**Comment by cpspicer** [comment]
Linked to #193

**Comment by NicoledeGreef** [comment]
addition of scrollbar would perhaps alleviate some of the stretch trouble with the lengthy query form.

**Comment by cpspicer** [comment]
Good solution @qqnluaq

**Comment by cpspicer** [comment]
link to #242

**Comment by cpspicer** [comment]
closing this issue - moving 242 into the backlog
